name: Straddle Test Suite CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - name: Run tests
        shell: bash
        env:
          ALCHEMY_TOKEN: ${{ secrets.ALCHEMY_TOKEN }}
        run: |
          npx hardhat test
